### PR TITLE
Add fonts to fix the problem that webui cannot display Chinese files …

### PR DESCRIPTION
**Pull request by baofeidyz**
Add fonts to fix the problem that webui cannot display Chinese files or folders when opening files.

Before:

After:

### CODE REVIEW

**Comment by jlesage** [comment]
Hello, this is already implemented via the `ENABLE_CJK_FONT` environment variable.
https://github.com/jlesage/docker-mediainfo?tab=readme-ov-file#environment-variables

**Comment by baofeidyz** [comment]
> [](https://github.com/jlesage/docker-mediainfo?tab=readme-ov-file#environment-variables)

Thanks for your reply. After you told me about the ENABLE_CJK_FONT environment variable, I tried to use it but failed due to limited network and inability to access the font cdn server.

```
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: installing CJK font...
[cont-init   ] 15-cjk-font.sh: fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
[cont-init   ] 15-cjk-font.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
[cont-init   ] 15-cjk-font.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
[cont-init   ] 15-cjk-font.sh: ERROR: unable to select packages:
[cont-init   ] 15-cjk-font.sh: Huh? Error reporter did not find the broken constraints.
[cont-init   ] 15-cjk-font.sh: terminated with error 2.
```
You can close my pull request if you want, it's ok, I'll fix this myself, thanks for your open source project, best wishes.

**Comment by jlesage** [comment]
This error has been fixed. Are you using the latest version of the image ?

**Comment by baofeidyz** [comment]
> This error has been fixed. Are you using the latest version of the image ?

I checked my image ID is 23d5486668f0 and the latest image ID is 74574d06c1d9. So I was using an old image and the reason was that I was running on unraid OS and the application had not been updated before. I forced an update of the image version and then the error was fixed. Thanks again for your reply!

**Pull request closed without merging**
